name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      # Wake up the server
      - uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: "https://blog.darkterra.io/rss"
      - uses: actions/checkout@v3.3.0
      # Make sure the server is wake up
      - uses: jakejarvis/wait-action@v0.1.1
        with:
          time: 30s
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://blog.darkterra.io/rss"
          
